// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBpA2C-sWJ8D3yErXcq2OW2wyPs4p7G1pA',
    appId: '1:481264951131:web:eabd6e4049d9eeabf5c47e',
    messagingSenderId: '481264951131',
    projectId: 'planitect-app',
    authDomain: 'planitect-app.firebaseapp.com',
    storageBucket: 'planitect-app.appspot.com',
    measurementId: 'G-9W3N3825N7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB4T5JDAQYds8wrJDuOWo74MX5LjQPpAtc',
    appId: '1:481264951131:android:26f341de8ca999a4f5c47e',
    messagingSenderId: '481264951131',
    projectId: 'planitect-app',
    storageBucket: 'planitect-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA4xx6yBJzpofk5rrMOnFv7AZ56hDR3zpg',
    appId: '1:481264951131:ios:b47a295b3deebddbf5c47e',
    messagingSenderId: '481264951131',
    projectId: 'planitect-app',
    storageBucket: 'planitect-app.appspot.com',
    iosClientId: '481264951131-fthh7394mua2uj83g21kd5b10nh563u4.apps.googleusercontent.com',
    iosBundleId: 'com.vthuynh.vanMainFlutterApp',
  );
}
